### ISSUE TITLE
Getting Error FORBIDDEN as an ApiException

### ISSUE THREAD

**Issue by mrcodecloud** [groupdocs-viewer-cloud/groupdocs-viewer-cloud-java-samples#3]
I am trying to build, and run the RenderLayer.java (https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-java-samples/blob/master/Examples/src/main/java/examples/AdvancedUsage/RenderingOptionsByFileType/RenderingCadDrawings/RenderLayers.java)  file, but getting Forbidden error from the Api, here I am sharing the Exception details as following 

ray@Ray groupdocs-viewer-cloud-java-samples-master %  cd /Users/ray/Downloads/groupdocs-viewer-cloud-java-samples-master ; /usr/bin/env /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:52100 -Dfile.encoding=UTF-8 @/var/folders/jk/fp3d2cfn0k527rnfk6ck86yc0000gn/T/cp_9fdvawq1k5d762z9vey4l0z70.argfile examples.AdvancedUsage.RenderingOptionsByFileType.RenderingCadDrawings.RenderLayers 
Exception: Forbidden
com.groupdocs.cloud.viewer.client.ApiException: Forbidden
        at com.groupdocs.cloud.viewer.client.ApiClient.handleResponse(ApiClient.java:892)
        at com.groupdocs.cloud.viewer.client.ApiClient.execute(ApiClient.java:786)
        at com.groupdocs.cloud.viewer.api.ViewApi.createViewWithHttpInfo(ViewApi.java:166)
        at com.groupdocs.cloud.viewer.api.ViewApi.createView(ViewApi.java:152)
        at examples.AdvancedUsage.RenderingOptionsByFileType.RenderingCadDrawings.RenderLayers.main(RenderLayers.java:33)

<img width="1226" alt="build error" src="https://user-images.githubusercontent.com/6930624/128847304-b10284e9-22dd-47f2-b812-a72a3609f58b.png">

**Comment by aspose-com-kb** [comment]
@RAZA-ABBBASI ,

Please post your query along with sample code and any related input/output files in our [free support forums](https://forum.groupdocs.cloud/). Thanks.

**Comment by mrcodecloud** [comment]
I was facing this due to exceeding the free limit assigned for APIs testing,
